pipeline:
  name: Build containerize-and-deploy-Java-app-to-Azure
  identifier: Build_containerize_and_deploy_Java_app_to_Azure_1709284417985
  projectIdentifier: Java_app_aks
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Welcome
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness Java App Deployment"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: build_push_java_app
                  identifier: build_push_java_app
                  spec:
                    connectorRef: umaran1218
                    repo: https://index.docker.io/v2/
                    tags:
                      - dev
                    dockerfile: Project /Airlines/Dockerfile
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: containerize-and-deploy-Java-app-to-Azure
        build: <+input>
