pipeline:
  name: Build containerize-and-deploy-Java-app-to-Azure
  identifier: Build_containerize_and_deploy_Java_app_to_Azure_1709284417985
  projectIdentifier: Java_app_aks
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Welcome
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness Java App Deployment"
              - step:
                  type: Run
                  name: mvn_install
                  identifier: mvn_install
                  spec:
                    shell: Sh
                    command: |-
                      cd Project/Airlines
                      mvn clean install
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: containerize-and-deploy-Java-app-to-Azure
        build: <+input>
