pipeline:
  name: Build containerize-and-deploy-Java-app-to-Azure
  identifier: Build_containerize_and_deploy_Java_app_to_Azure_1709284417985
  projectIdentifier: Java_app_aks
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Welcome
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness Java App Deployment"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: build_push_java_app
                  identifier: build_push_java_app
                  spec:
                    connectorRef: umaran1218
                    repo: umaran1218/flightbookingsystemsample
                    tags:
                      - dev
                    dockerfile: Project/Airlines/Dockerfile
              - step:
                  type: Run
                  name: az_login
                  identifier: az_login
                  spec:
                    shell: Sh
                    command: az login
              - step:
                  type: Run
                  name: install_aks_cli
                  identifier: install_aks_cli
                  spec:
                    shell: Sh
                    command: az aks install-cli
              - step:
                  type: Run
                  name: aks_helm_deploy
                  identifier: aks_deploy
                  spec:
                    shell: Sh
                    command: |-
                      az aks get-credentials --resource-group epp-uma --name epp-aks
                      helm install epp-uma Project/Airlines/java-app/ --values Project/Airlines/java-app/values.yaml
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: containerize-and-deploy-Java-app-to-Azure
        build: <+input>
